"""Remove unique constraint from number_of_pages

Revision ID: a12cc27d92dd
Revises: b52d21171705
Create Date: 2025-05-07 15:57:34.194456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a12cc27d92dd'
down_revision = 'b52d21171705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('number_of_pages',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('price_unit',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_index('number_of_pages')
        batch_op.drop_index('price_unit')

    with op.batch_alter_table('companys', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companys', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index('price_unit', ['price_unit'], unique=True)
        batch_op.create_index('number_of_pages', ['number_of_pages'], unique=True)
        batch_op.alter_column('price_unit',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('number_of_pages',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
