"""Add authors_id to companys

Revision ID: b52d21171705
Revises: d64a8cb3eb48
Create Date: 2025-05-06 15:46:16.448483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b52d21171705'
down_revision = 'd64a8cb3eb48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_constraint('authors_ibfk_1', type_='foreignkey')
        batch_op.drop_column('authors_id')

    with op.batch_alter_table('companys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authors_id', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('origin',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.drop_constraint('companys_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'authors', ['authors_id'], ['id'])
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('companys_ibfk_1', 'authors', ['author_id'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('origin',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('authors_id')

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authors_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('authors_ibfk_1', 'authors', ['authors_id'], ['id'])

    # ### end Alembic commands ###
